title: C++への導入
description: Web Document for C++ syoshinsya in Denkoken.

theme: jekyll-theme-cayman

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

  syntax_highlighter_opts:
    css_class: 'hljs'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
    gutter_class: 'mycodetable'
    code_class: 'mycodetable'
