title: C++への導入
description: Web Document for C++ syoshinsya in Denkoken.

theme: jekyll-theme-cayman

markdown: kramdown
highlighter: rouge

kramdown:
  use_coderay: true

  coderay:
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_css: style
